version: '3.8'

services:
  vivi-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/panku/Vivi/src
      #- ./nodemon.json:/home/node/app/nodemon.json
    container_name: vivi-docker
    command: node build/src/index.js
