import { Message } from "discord.js";

const viviFacts = [
    "Banging your head against a wall for one hour burns 150 calories.",
    "In Switzerland it is illegal to own just one guinea pig.",
    "Pteronophobia is the fear of being tickled by feathers.",
    "Snakes can help predict earthquakes.",
    "A flock of crows is known as a murder.",
    "The oldest “your mom” joke was discovered on a 3,500 year old Babylonian tablet.",
    "So far, two diseases have successfully been eradicated: smallpox and rinderpest.",
    "29th May is officially “Put a Pillow on Your Fridge Day”.",
    "Cherophobia is an irrational fear of fun or happiness.",
    "7% of American adults believe that chocolate milk comes from brown cows.",
    "If you lift a kangaroo’s tail off the ground it can’t hop.",
    "Bananas are curved because they grow towards the sun.",
    "The inventor of the Frisbee was cremated and made into a Frisbee after he died.",
    "During your lifetime, you will produce enough saliva to fill two swimming pools.",
    "If Pinocchio says “My Nose Will Grow Now”, it would cause a paradox.",
    "Polar bears could eat as many as 86 penguins in a single sitting...",
    "King Henry VIII slept with a gigantic axe beside him.",
    "Movie trailers were originally shown after the movie, which is why they were called “trailers”.",
    "An eagle can kill a young deer and fly away with it.",
    "Heart attacks are more likely to happen on a Monday.",
    "The longest national anthem is the Greek national anthem, with 158 verses.",
    "An average pencil can draw a line up to 35 miles long before running out.",
    "Of all the animals on Earth, the mosquito has contributed to more deaths than any other animal.",
    "The strongest muscle in the human body, proportional to its size, is the tongue.",
    "The painting 'Mona Lisa' actually has no eyebrows or eyelashes.",
    "Ironically, buttermilk does not contain any butter.",
    "Methane gases produced by cows create just as much pollution as cars do.",
    "Jackie Chan's parents met when his father arrested his mother for smuggling opium.",
    "New York paid $5 million for a piece of land that is now worth over $530 billion, which is known today as Central Park.",
    "Farting reduces blood pressure and is good for your overall health.",
    "Only 8% of the world's money exists in the physical form.",
    "The first modern toilet was designed by Thomas Crapper.",
    "Carrots were originally purple until the 17th century where a mutation caused them to turn orange.",
    "Skins of honey badgers are thick enough to withstand strikes from swords, arrows and spears.",
    "There's an Adidas shoe store in Amsterdam that's shaped like a shoe box.",
    "dustpan does its job even when you're not using it",
    "A lethal dose is also a lifetime supply",
    "You will never know the memories you've forgotten",
    "Surgery is just stabbing someone to life",
    "When you say forward or back your lips move in that direction",
    "In a fake time machine you still come out in the future",
    "Any stairway is a stairway to heaven if you're clumsy enough",
    "Cheese is just a loaf of milk",
    "You're not ugly, you're just not your type",
    "Second-guessing yourself is your brain telling your brain not to listen to your brain",
    "Everything that you have ever lost is still somewhere",
    "The night is the natural state of the universe the day is just an anomaly created by the Sun",
    "The number of people older than you is constantly shrinking",
    "Food doesn't go bad something else just starts eating it before you do",
    "You're always starving to death eating just resets the timer",
    "Maybe time travelers have already changed history and our past is what they think is acceptable",
    "Falling down is basically getting hit by a planet",
    "Houseplants are just pet vegetables",
    "Too many birthdays will kill you",
    "The fact that glasses didn't exist for so long explains a lot of historical myths and legends",
    "You could throw a rock into a lake and be the last person to ever touch that rock for all of time",
    "Given the current state of our oceans instead of saying there's plenty of fish in the sea people can say there's some fish still left among the trash which is probably a better metaphor anyways",
    "You're just a background character in someone else's life",
    "At any given moment your future self could be thinking about you",
    "Art is how we decorate space, music is how we decorate time",
    "If everyone in the world participated in a rock-paper-scissors tournament the winner would only have to win 33 straight games",
    "Every light switch is also a dark switch",
    "Technically lamps in videogames use real electricity",
    "Listening to a single instrument in a song is like staring but with your ears"
];

const fact = {
	desc: "Have vivi send you a fact",
	name: "fact",
	args: "",
	type: "general",
	run: (message: Message) => {
        message.delete();
        const facts = viviFacts[Math.floor(Math.random() * viviFacts.length)];
        message.reply(`${facts}`)
    }
}

export default fact;